### PR TITLE
bump version to 1.1-SNAPSHOT intercept deployment problem to throw DeploymentException to be able to intercept deployment issues

### PR DESCRIPTION
**Pull request by olamy**
Signed-off-by: Olivier Lamy <olamy@apache.org>

### CODE REVIEW

**Review by arjantijms — CHANGES_REQUESTED** [review]
LGTM, although CommonGlassFishManager.java shows up as one big difference. Looking at it without ws changes makes the actual change visible. Might be line-endings.

**Comment by olamy** [comment]
> LGTM, although CommonGlassFishManager.java shows up as one big difference. Looking at it without ws changes makes the actual change visible. Might be line-endings.

and obviously this is the file I changed 😩.
I restored but editing it always change everything. not sure what is the problem but the add then first commit of this file seems to be a problem.
I need to find a way to edit this....

**Comment by arjantijms** [comment]
> I restored but editing it always change everything

Maybe just a setting in your IDE? Anyway, it looks good now ;)

**Review by arjantijms — APPROVED** [review]

**Comment by olamy** [comment]
> > I restored but editing it always change everything
> 
> Maybe just a setting in your IDE? Anyway, it looks good now ;)
that's weird :) 

Thanks for merging!

**Pull request merged**
